# MBT Crystallization (Chai et. al, 2020)
mbt:
  name: "MBT"
  building_blocks: [1,2,3,4,15,22,29,42,123]
  constraints:
    NUM_GROUPS:
      min: 3
      max: 8
    NUM_REPEAT_GROUPS:
      min: 0
      max: 7
    NUM_FUNC_GROUPS: 
      min: 1
      max: 6
    MOLECULAR_WEIGHT: 
      min: 80
      max: 200
    FLASH_POINT:
      min: 273
      max: 393
    MELTING_POINT:
      min: 173
      max: 310
    BOILING_POINT:
      min: 373
      max: 600
    LC50:
      min: 0
      max: 4.8
    HSP:
      min: 18
      max: 21
  num_rings: all
  level: 1

# Surfactant Design, Mattei et al. (2014) and Seider et al. (2017) 
surfactant:
  name: "Surfactant"
  building_blocks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 21, 22]
  constraints:
    NUM_GROUPS:
      min: 20
      max: 30
    NUM_REPEAT_GROUPS:
      min: 0
      max: 15
    NUM_FUNC_GROUPS: 
      min: 6
      max: 10
    MOLECULAR_WEIGHT: 
      min: 300
    MELTING_POINT:
      min: 300
    BOILING_POINT:
      min: 400
    LC50:
      min: 0
      max: 4
  num_rings: all
  level: 1

# Surfactant Design (DCM Replacement), Gani et al. (2005) and Seider et al. (2017)
# acyclic only!!!
DCM:
  name: "DCM"
  building_blocks: [1, 2, 3, 4, 29, 33, 34, 38, 40, 41, 44, 48, 49, 50, 51]
  constraints:
    NUM_GROUPS:
      min: 2
      max: 8
    NUM_REPEAT_GROUPS:
      min: 0
      max: 2
    NUM_FUNC_GROUPS: 
      min: 1
      max: 3
    MOLECULAR_WEIGHT: 
      min: 0
    MELTING_POINT:
      min: 250
    BOILING_POINT:
      min: 325
      max: 425
    HSP:
      min: 16
      max: 19
  num_rings: all
  level: 1

# Refrigerant Design, Seider et al., 2017
refrigerant:
  name: "Refrigerant"
  building_blocks: [1, 2, 3, 4, 116, 118, 119, 120, 121, 122]
  objective: ["max", "ENTHALPY_VAPORIZATION"]
  constraints:
    NUM_GROUPS:
      min: 2
      max: 6
    NUM_REPEAT_GROUPS:
      min: 0
      max: 2
    BOILING_POINT:
      max: 250
    CRITICAL_TEMP:
      min: 300
      max: 390
    CRITICAL_PRESSURE:
      min: 30
      max: 50
    ENTHALPY_VAPORIZATION:
      min: 16
    VAPOR_PRESSURE:
      min: 550
  num_rings: all
  level: 1

# H2S/CO2 Absorbent Design, Liu et. al 2019
# Need to add functionality to support constraints on specific groups & specific atoms
absorbent:
  name: "Absorbent"
  building_blocks: [1, 2, 3, 4, 29, 54, 55, 56, 57, 58, 59, 60, 61]
  objective: ["min", "LC_50"]
  constraints:
    NUM_GROUPS:
      min: 3
      max: 6
    NUM_REPEAT_GROUPS:
      min: 0
      max: 3
    NUM_FUNC_GROUPS:
      29:
        min: 1
      'N':
        min: 1
    MOLECULAR_WEIGHT: 
      max: 140
    FLASH_POINT:
      min: 360
    MELTING_POINT:
      max: 325
    BOILING_POINT:
      min: 460
    ENTHALPY_FORMATION:
      max: -200
    VAPOR_PRESSURE:
      max: 500
    HSP:
      min: 25
      max: 30
    VISCOSITY:
      max: 100
    LC50:
      max: 2.5
  num_rings: all
  level: 1