hp:
  num_iterations: 10000
  collect_episodes_per_iteration: 2
  replay_buffer_capacity: 2000
  fc_layer_params: 100
  learning_rate: .003
  log_interval: 25
  num_eval_episodes: 200
  eval_interval: 50
  max_steps: 20

alg_defaults:
  enable_rf: true
  enable_a2c: false
  enable_ppo: false
  enable_sac: false
  enable_dqn: false
  enable_ddpg: false
  enable_trpo: false
  enable_soft_constraints: false

scoring:
  reward: 'l1'

log:
  root: "./"

total_groups:
  NUM_FIRST_ORDER: 220
  NUM_SECOND_ORDER: 130
  NUM_THIRD_ORDER: 74
  UNBOUNDED: 9999999
